"""
MNH-MoH indicator definitions, relocated from mnid/core/indicators.py
(_program_based_priority_indicators) where they previously lived inline,
filtered out of the default runtime list via include_moh=False and the
'_moh_' id substring check (see _enrich_program_based_mnid_indicators).
Moved here so the MoH indicator set is a real, separate file instead of
a runtime-filtered subset of the shared (beginnings) list.

Status:
  tracked           - calculated from MAHIS data
  overview_only     - shown as a summary count, not a tracked % card
  awaiting_baseline - data not yet in this extract
"""


def get_mnh_moh_indicators():
    return [
        {'id': 'mnid_anc_moh_001',
         'label': 'Clients registered at facility',
         'category': 'ANC',
         'target': 80,
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_002',
         'label': 'New ANC registrations',
         'category': 'ANC',
         'target': 80,
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'new_revisit', 'value2': 'new'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_003',
         'label': 'Continuing ANC clients',
         'category': 'ANC',
         'target': 80,
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'new_revisit', 'value2': 'revisit'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_004',
         'label': 'Ultrasound scanning performed',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_pocus_with_ga', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_005',
         'label': 'HIV positive clients',
         'category': 'ANC',
         'target': 5,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_hiv_positive', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_006',
         'label': 'HIV positive clients on ART',
         'category': 'ANC',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_hiv_positive', 'value2': 'Yes', 'variable3': 'mnid_anc_hiv_on_art', 'value3': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_hiv_positive', 'value2': 'Yes'}},
        {'id': 'mnid_anc_moh_007',
         'label': 'Tested for syphilis',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_syphilis_tested', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_008',
         'label': 'Screened for Hepatitis B',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_hepatitis_b_tested', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_009',
         'label': 'Tested for Haemoglobin level',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_hb_screened', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_010',
         'label': 'Previous uterine scars',
         'category': 'ANC',
         'target': 15,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'screening',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_previous_uterine_scar', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_011',
         'label': 'Started ANC in first trimester (0-12 weeks)',
         'category': 'ANC',
         'target': 40,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_first_trimester', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_012',
         'label': '4+ ANC contacts',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_anc_4plus_contacts', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_013',
         'label': 'Received 3+ doses of SP',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_sp_3plus', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_014',
         'label': 'Received 180+ MMS tablets',
         'category': 'ANC',
         'target': 60,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_mms_180plus', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_015',
         'label': 'Received 120+ FeFo tablets',
         'category': 'ANC',
         'target': 60,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_fefo_120plus', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_016',
         'label': 'Received ITN during ANC',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_itn_given', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_anc_moh_017',
         'label': 'New ANC registrations by age group (<18)',
         'category': 'ANC',
         'target': 80,
         'level': 'tertiary',
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'new_revisit', 'value2': 'new', 'variable3': 'Age_Group', 'value3': '15-24'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'new_revisit', 'value2': 'new'}},
        {'id': 'mnid_anc_moh_018',
         'label': 'Received 2+ doses of TdV',
         'category': 'ANC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'clinical',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC', 'variable2': 'mnid_anc_tdv_2plus', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'ANC'}},
        {'id': 'mnid_lab_moh_001',
         'label': 'Delivered at this facility',
         'category': 'Labour',
         'target': 80,
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_facility_birth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_002',
         'label': 'Delivered at home or in transit',
         'category': 'Labour',
         'target': 5,
         'target_mode': 'min',
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_home_birth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_003',
         'label': 'Institutional maternal deaths',
         'category': 'Labour',
         'target': 0,
         'target_mode': 'min',
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_004',
         'label': 'HIV positive clients in Labour',
         'category': 'Labour',
         'target': 5,
         'target_mode': 'min',
         'status': 'overview_only',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_hiv_positive', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_005',
         'label': 'Delivered by skilled attendant',
         'category': 'Labour',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'delivery_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_skilled_attendant', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_006',
         'label': 'Normal vaginal delivery',
         'category': 'Labour',
         'target': 60,
         'status': 'tracked',
         'sub_category': 'delivery_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_normal_delivery', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_007',
         'label': 'Maternal death due to PPH',
         'category': 'Labour',
         'target': 0,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'mortality',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death_pph', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_008',
         'label': 'Maternal death due to Sepsis',
         'category': 'Labour',
         'target': 0,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'mortality',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death_sepsis', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_009',
         'label': 'Maternal death due to Eclampsia',
         'category': 'Labour',
         'target': 0,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'mortality',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death_eclampsia', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_010',
         'label': 'Maternal death due to Obstructed labour',
         'category': 'Labour',
         'target': 0,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'mortality',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death_obstructed', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_011',
         'label': 'Obstetric complication: PPH',
         'category': 'Labour',
         'target': 15,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_pph', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_012',
         'label': 'Obstetric complication: Eclampsia',
         'category': 'Labour',
         'target': 7,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_eclampsia', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_013',
         'label': 'Obstetric complication: Obstructed labour',
         'category': 'Labour',
         'target': 8,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_obstructed_labour', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_014',
         'label': 'Obstetric complication: Maternal sepsis',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_sepsis', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_015',
         'label': 'HIV positive on ART in Labour',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'hiv_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_hiv_on_art', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_hiv_positive', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_016',
         'label': 'Exposed babies on ART prophylaxis',
         'category': 'Labour',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'hiv_care',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_arv_prophylaxis', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_017',
         'label': 'Fresh stillbirth rate',
         'category': 'Labour',
         'target': 50,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'outcomes',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_fresh_stillbirth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_total_birth', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_018',
         'label': 'Macerated stillbirth rate',
         'category': 'Labour',
         'target': 50,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'outcomes',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_macerated_stillbirth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_total_birth', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_019',
         'label': 'Live births',
         'category': 'Labour',
         'target': 90,
         'status': 'tracked',
         'sub_category': 'outcomes',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_live_birth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_020',
         'label': 'Neonatal death rate',
         'category': 'Labour',
         'target': 50,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'outcomes',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_neonatal_death', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_021',
         'label': 'Clients referred to another facility',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'referrals',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referred_out', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_022',
         'label': 'Referral due to PPH',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'referrals',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referral_pph', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referred_out', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_023',
         'label': 'Referral due to Eclampsia',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'referrals',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referral_eclampsia', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referred_out', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_024',
         'label': 'Referral due to Obstructed labour',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'referrals',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referral_obstructed', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referred_out', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_025',
         'label': 'Referral due to Sepsis',
         'category': 'Labour',
         'target': 10,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'referrals',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referral_sepsis', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_referred_out', 'value1': 'Yes'}},
        {'id': 'mnid_lab_moh_026',
         'label': 'Delivered at this facility',
         'category': 'Labour',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'delivery_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_facility_birth', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_027',
         'label': 'Maternal Mortality Ratio (MMR)',
         'category': 'Labour',
         'target': 70,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'delivery_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_maternal_death', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_live_birth', 'value1': 'Yes'},
         'format': 'per_100k'},
        {'id': 'mnid_lab_moh_028',
         'label': 'Signal: Parenteral antibiotics',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_antibiotics', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_029',
         'label': 'Signal: Anticonvulsants (MgSO4)',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_magnesium_sulphate', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_030',
         'label': 'Signal: Oxytocics',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_uterotonic_given', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_031',
         'label': 'Signal: Manual placenta removal',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_manual_placenta', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_032',
         'label': 'Signal: MVA / retained products',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_mva', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_033',
         'label': 'Signal: Assisted vaginal delivery',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_assisted_delivery', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_034',
         'label': 'Signal: Neonatal resuscitation',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_resuscitation', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_035',
         'label': 'Signal: Caesarean section',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_csection', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_lab_moh_036',
         'label': 'Signal: Blood transfusion',
         'category': 'Labour',
         'target': 95,
         'status': 'tracked',
         'sub_category': 'signal_functions',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_labour_signal_blood_transfusion', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Labour'}},
        {'id': 'mnid_pnc_moh_001',
         'label': 'Mothers admitted to postnatal ward',
         'category': 'PNC',
         'target': 80,
         'status': 'overview_only',
         'sub_category': 'admissions',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_mother_admitted', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'PNC'}},
        {'id': 'mnid_pnc_moh_002',
         'label': 'Babies admitted to postnatal ward',
         'category': 'PNC',
         'target': 80,
         'status': 'overview_only',
         'sub_category': 'admissions',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_baby_admitted', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'PNC'}},
        {'id': 'mnid_pnc_moh_003',
         'label': 'Mothers with postnatal complications',
         'category': 'PNC',
         'target': 15,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_mother_complication', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_004',
         'label': 'Babies with postnatal complications',
         'category': 'PNC',
         'target': 15,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'complications',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_newborn_complication', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_005',
         'label': 'LBW babies receiving KMC',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'nutrition',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_kmc_for_lbw', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_underweight', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_006',
         'label': 'Mothers checked within 7 days',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'follow_up',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_check_7days', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_007',
         'label': 'Babies checked within 7 days',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'follow_up',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_check_7days', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_008',
         'label': 'Mothers checked at 6 weeks',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'follow_up',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_check_6weeks', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_009',
         'label': 'Babies checked at 6 weeks',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'follow_up',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_check_6weeks', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_010',
         'label': 'Immediate postpartum family planning',
         'category': 'PNC',
         'target': 60,
         'status': 'tracked',
         'sub_category': 'family_planning',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_family_planning', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_011',
         'label': 'HIV positive postnatal mothers',
         'category': 'PNC',
         'target': 5,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'hiv_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_hiv_test_positive', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_012',
         'label': 'HIV exposed babies',
         'category': 'PNC',
         'target': 5,
         'target_mode': 'min',
         'status': 'overview_only',
         'sub_category': 'hiv_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_hiv_exposed_baby', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'PNC'}},
        {'id': 'mnid_pnc_moh_013',
         'label': 'HIV exposed babies on ART prophylaxis',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'hiv_care',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_art_prophylaxis_baby', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_hiv_exposed_baby', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_014',
         'label': 'Babies who received BCG',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'immunization',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_bcg', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_015',
         'label': 'Babies who received Polio 0',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'immunization',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_polio_0', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_016',
         'label': 'Underweight babies',
         'category': 'PNC',
         'target': 15,
         'target_mode': 'min',
         'status': 'overview_only',
         'sub_category': 'nutrition',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_underweight', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'PNC'}},
        {'id': 'mnid_pnc_moh_016b',
         'label': 'Underweight babies (percentage)',
         'category': 'PNC',
         'target': 15,
         'target_mode': 'min',
         'status': 'tracked',
         'sub_category': 'nutrition',
         'level': 'tertiary',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_underweight', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
        {'id': 'mnid_pnc_moh_017',
         'label': 'Exclusive breastfeeding counselling',
         'category': 'PNC',
         'target': 80,
         'status': 'tracked',
         'sub_category': 'nutrition',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_exclusive_breastfeeding', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_pnc_visit_documented', 'value1': 'Yes'}},
    ]
