"""
Nest360 indicator definitions.

26 original entries carry real numerator/denominator_filters where MAHIS
has a verified concept for them. The rest were added from the NEST-IT
Clinical & Implementation Indicators Guide (Indicators Guide (1).docx,
last updated 3 Aug 2026) and are NEST-IT NID/Context Tracker system fields
(in_glu_adm_doc, tr_eqt_cp_cp_fc, ...), not MAHIS concepts -- they carry no
filters and stay awaiting_baseline, with the real numerator/denominator
language from the Guide in their note instead of fabricated MAHIS filters.

Country-specific entries in the Guide (e.g. "Malawi, Nigeria, Tanzania &
Ethiopia" vs "Kenya only" for the same indicator) took the Malawi-labeled
definition; Kenya-only variants were dropped. Unlabeled entries apply to
all countries and were included as-is.

Devices & Supplies / Infrastructure / Human Resources indicators from the
Guide were deliberately left out -- that is operational readiness's
territory (see mnid/views/operational_readiness.py and
validated_dashboard.json's supply_indicators/workforce_indicators/
data_quality_indicators), not something Nest360 should duplicate.

Some of these ARE populated today for 7 specific Malawi facilities via
data/excel/NEST_BF_facilitites.xlsx -> mnid/dhis2/tools/excel_to_dhis2_parquet.py
(merged directly into the DHIS2 aggregate, not computed from MAHIS rows --
see that scripts METRIC_TO_DHIS2 mapping and mnid_nb_core_* ids for which
ones).

Status:
  tracked           - calculated from MAHIS data
  overview_only     - shown as a summary count, not a tracked % card
  awaiting_baseline - data not yet in this extract
"""


def get_nest360_indicators():
    return [
        # --- Vital signs -------------------------------------------------
        {'id': 'nest360_pulse_oximeter_used_at_admission',
         'label': 'Pulse oximeter used at admission',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn', 'variable2': 'mnid_newborn_pulse_oximeter_admission', 'value2': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_temperature_taken_at_admission',
         'label': 'Temperature taken at admission',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Verified against MAHIS-FRONT (src/apps/Neonatal/config/vitals.ts): neither raw temperature nor a categorical thermal-status concept flows into this extract -- "Thermal status on admission" '
                 'is not a real MAHIS concept. No real data source for this indicator currently.'},
        {'id': 'nest360_weight_taken_at_birth',
         'label': 'Weight taken at birth',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'Birth weight'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_glucose_monitored_at_admission',
         'label': 'Glucose monitored at admission',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 75,
         'status': 'awaiting_baseline',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'note': 'Babies who had a blood glucose measurement taken when admitted to the neonatal unit / Total number of babies admitted to the neonatal unit. Per NEST-IT Clinical & Implementation Indicators '
                 'Guide (Indicators Guide (1).docx), last updated 3 Aug 2026. Target >=75% (varies by case mix).'},
        {'id': 'nest360_weight_taken_at_admission',
         'label': 'Weight taken at admission',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Babies who had their weight taken when admitted to the neonatal unit / Total number of babies admitted to the neonatal unit. Per NEST-IT Clinical & Implementation Indicators Guide '
                 '(Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_glucose_monitored_during_stay',
         'label': 'Glucose monitored during stay',
         'category': 'Nest360',
         'subcategory': 'Vital signs',
         'target': 75,
         'status': 'awaiting_baseline',
         'note': 'Babies who had a blood glucose measurement taken during their stay in the neonatal unit / Total number of babies admitted to the neonatal unit. Per NEST-IT Clinical & Implementation '
                 'Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- CPAP --------------------------------------------------------
        {'id': 'nest360_cpap_for_eligible_babies',
         'label': 'CPAP for eligible babies',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'CPAP support'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_cpap_for_babies_1000_1499g',
         'label': 'CPAP for babies 1000-1499g (prophylactic)',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_cpap_1000_1499', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_birth_weight_band', 'value1': '1000-1499g'}},
        {'id': 'nest360_cpap_1500_1999g_with_symptoms',
         'label': 'CPAP 1500-1999g (with symptoms)',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_cpap_1500_1999', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_birth_weight_band', 'value1': '1500-1999g'}},
        {'id': 'nest360_cpap_timing_birth',
         'label': 'Time: Birth to CPAP initiation (1000-1999g)',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': 100,
         'status': 'awaiting_baseline',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_cpap_admission_timing',
         'label': 'Time: Admission to CPAP initiation (1000-1999g)',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Babies 1000-1999g who received CPAP, by time from admission to CPAP initiation (<=1h, 1-4h, 4-12h, 12-24h, >24h, missing) / Total number of babies (1000-1999g) who received CPAP. Per '
                 'NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_cpap_done_mortality',
         'label': 'CPAPs done and mortality',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Babies who received CPAP during their ward stay and later died, regardless of cause / Total number of babies who had CPAP (all weights, by weight category). Per NEST-IT Clinical & '
                 'Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_cpap_types',
         'label': 'CPAP types used',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Number of treatments using each CPAP type (improvised bubble, blended non-humidified, blended+humidified, blended+heated+humidified, ventilator in nasal CPAP mode, not documented) / Total '
                 'count of CPAP treatments. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026. Malawi, Nigeria, Tanzania and Ethiopia.'},
        {'id': 'nest360_cpap_treatment_combined',
         'label': 'CPAP Treatment (combined)',
         'category': 'Nest360',
         'subcategory': 'CPAP',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Sum of the CPAP for eligible babies + CPAP 1000-1499g numerators / Sum of the CPAP for eligible babies + CPAP 1000-1499g denominators. Per NEST-IT Clinical & Implementation Indicators '
                 'Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- KMC ---------------------------------------------------------
        {'id': 'nest360_kmc_1000_1999g',
         'label': 'KMC 1000-1999g',
         'category': 'Nest360',
         'subcategory': 'KMC',
         'target': 75,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_kmc', 'value1': 'Yes', 'variable2': 'mnid_birth_weight_band', 'value2': '1000-1499g'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_lbw_kmc_eligible', 'value1': 'Yes'}},
        {'id': 'nest360_kmc_2000_2499g',
         'label': 'KMC 2000-2499g',
         'category': 'Nest360',
         'subcategory': 'KMC',
         'target': 75,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_kmc', 'value1': 'Yes', 'variable2': 'mnid_birth_weight_band', 'value2': '2000-2499g'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_birth_weight_band', 'value1': '2000-2499g'}},
        {'id': 'nest360_kmc_timing',
         'label': 'Time: Birth to KMC initiation (1000-2500g)',
         'category': 'Nest360',
         'subcategory': 'KMC',
         'target': 100,
         'status': 'awaiting_baseline',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},

        # --- Hypothermia -------------------------------------------------
        {'id': 'nest360_not_hypothermic_at_admission',
         'label': 'Not hypothermic at admission',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Verified against MAHIS-FRONT (src/apps/Neonatal/config/vitals.ts): neither raw temperature nor a categorical thermal-status concept flows into this extract -- "Thermal status on admission" '
                 'is not a real MAHIS concept. No real data source for this indicator currently.'},
        {'id': 'nest360_thermal_care_recorded',
         'label': 'Thermal care recorded',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'thermal care'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_not_hypothermic_after_admission',
         'label': 'Not hypothermic after admission (excl. at admission)',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Babies with body temperature >=36.5C at any time during their stay, EXCLUDING at admission / Babies who had temperature taken at any time during their stay, EXCLUDING at admission. Per '
                 'NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_not_hypothermic_inborn',
         'label': 'Not hypothermic at admission, inborn',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies with body temperature >=36.5C when admitted to the neonatal unit / Inborn babies admitted who had their temperature taken at admission. Per NEST-IT Clinical & Implementation '
                 'Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_not_hypothermic_outborn',
         'label': 'Not hypothermic at admission, outborn',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Outborn babies with body temperature >=36.5C when admitted to the neonatal unit / Outborn babies admitted who had their temperature taken at admission. Per NEST-IT Clinical & '
                 'Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_thermal_status_distribution',
         'label': 'Thermal status at admission (distribution)',
         'category': 'Nest360',
         'subcategory': 'Hypothermia',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Distribution across Fever >=37.5C, Normal 36.5-37.4C, Mild Hypothermia 36-36.4C, Moderate 32-35.9C, Severe <32C / Total number of babies admitted who had temperature taken at admission. '
                 'Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- Jaundice ----------------------------------------------------
        {'id': 'nest360_phototherapy_for_jaundice',
         'label': 'Phototherapy for clinical jaundice',
         'category': 'Nest360',
         'subcategory': 'Jaundice',
         'target': 90,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_jaundice_phototherapy', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_jaundice', 'value1': 'Yes'}},
        {'id': 'nest360_bilirubin_measurement',
         'label': 'Bilirubin measured in babies with jaundice',
         'category': 'Nest360',
         'subcategory': 'Jaundice',
         'target': 80,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_jaundice_bilirubin_measured', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_jaundice', 'value1': 'Yes'}},
        {'id': 'nest360_exchange_transfusion',
         'label': 'Exchange Transfusion',
         'category': 'Nest360',
         'subcategory': 'Jaundice',
         'target': 100,
         'status': 'awaiting_baseline',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},

        # --- Infection ---------------------------------------------------
        {'id': 'nest360_neonatal_sepsis_rate',
         'label': 'Neonatal sepsis among admissions',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': 10,
         'status': 'tracked',
         'target_mode': 'min',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_sepsis', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_antibiotics_for_sepsis',
         'label': 'Antibiotics for clinical sepsis',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': 100,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_sepsis_antibiotics', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_sepsis', 'value1': 'Yes'}},
        {'id': 'nest360_blood_culture',
         'label': 'Blood culture done for babies on antibiotics',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': 100,
         'status': 'awaiting_baseline',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_facilities_doing_blood_culture',
         'label': 'Facilities doing blood culture',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Number of facilities that did at least 1 blood culture test / Total number of reporting facilities. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last '
                 'updated 3 Aug 2026.'},
        {'id': 'nest360_antibiotics_classification',
         'label': 'Antibiotics classification (AWaRe)',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Antibiotics administered classified under WHO AWaRe categories / Total prescribed antibiotics. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last '
                 'updated 3 Aug 2026.'},
        {'id': 'nest360_blood_culture_results_recorded',
         'label': 'Blood culture results recorded',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': 100,
         'status': 'awaiting_baseline',
         'note': 'Babies who had blood culture done and recorded a positive or negative result / Babies who had blood culture test done. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators '
                 'Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_positive_blood_culture_rate',
         'label': 'Positive blood culture rate',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Number of babies with a positive blood culture result / Total number of cultures done. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 '
                 'Aug 2026.'},
        {'id': 'nest360_probable_contaminants_rate',
         'label': 'Probable contaminants among positive cultures',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Number of babies with probable contaminants identified / Number of babies with a positive blood culture result. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide '
                 '(1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_microorganism_distribution',
         'label': 'Microorganisms identified in positive cultures',
         'category': 'Nest360',
         'subcategory': 'Infection',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Count per organism group (S. aureus, Klebsiella, Pseudomonas, E. coli, Acinetobacter, other gram+/-, fungal, unclassified, not documented) / Total number of microorganisms found in '
                 'positive cultures. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- Nutrition ---------------------------------------------------
        {'id': 'nest360_breastmilk_day_of_birth',
         'label': 'Breastmilk on day of birth',
         'category': 'Nest360',
         'subcategory': 'Nutrition',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Babies who got breastmilk on their day of birth / Babies admitted (excl. deaths on day of admission). Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), '
                 'last updated 3 Aug 2026.'},
        {'id': 'nest360_exclusive_breastmilk_discharge',
         'label': 'Exclusive breastmilk at discharge',
         'category': 'Nest360',
         'subcategory': 'Nutrition',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Babies exclusively on breastmilk at discharge / Admissions with complete feeding-at-discharge data. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last '
                 'updated 3 Aug 2026.'},
        {'id': 'nest360_hypoglycemia_rate',
         'label': 'Not hypoglycemic (blood sugar documented)',
         'category': 'Nest360',
         'subcategory': 'Nutrition',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Babies not hypoglycemic (blood sugar <=2.5mmol/L / 45mg/dL is hypoglycemic) / Babies with documented blood sugar. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide '
                 '(1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_feeding_method_distribution',
         'label': 'Feeding method distribution at discharge',
         'category': 'Nest360',
         'subcategory': 'Nutrition',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Distribution across exclusive breastmilk / formula only / fortified breastmilk / predominant breastmilk / combination / unknown / missing / Admissions with complete feeding-at-discharge '
                 'data. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- Data Quality ------------------------------------------------
        {'id': 'nest360_data_completeness',
         'label': 'Data completeness (birth weight proxy)',
         'category': 'Nest360',
         'subcategory': 'Data Quality',
         'target': 95,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'Birth weight'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_data_entry_delays',
         'label': 'Data entry delays',
         'category': 'Nest360',
         'subcategory': 'Data Quality',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Records entered, categorized 0-1wk/1-2wk/2-4wk/4-6wk/6-8wk/8-12wk/12+wk / Total records. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 '
                 'Aug 2026.'},
        {'id': 'nest360_data_validity',
         'label': 'Data validity',
         'category': 'Nest360',
         'subcategory': 'Data Quality',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Valid entries (excl. NAs, within reasonable ranges) for discharge date, birthweight, lowest temp, lowest O2 sat / Total entries for those same variables. Per NEST-IT Clinical & '
                 'Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- Admissions & Mortality --------------------------------------
        {'id': 'nest360_neonatal_mortality_rate',
         'label': 'Neonatal mortality rate',
         'category': 'Nest360',
         'subcategory': 'Admissions & Mortality',
         'target': None,
         'status': 'tracked',
         'note': 'Same verified mnid_newborn_neonatal_death flag mnid_nb_overview_002 already uses. Upgraded from awaiting_baseline once confirmed real.',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_neonatal_death', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_mortality_by_birthweight',
         'label': 'Mortality by birthweight',
         'category': 'Nest360',
         'subcategory': 'Admissions & Mortality',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Neonatal unit deaths per birthweight band (<1000/1000-1499/1500-1999/2000-2499/2500-4000/4001+/not recorded) / Neonatal unit admissions per the same birthweight band. Per NEST-IT Clinical '
                 '& Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},

        # --- Maternal-Newborn Dyad ---------------------------------------
        {'id': 'nest360_neonatal_mortality_rate_inborn',
         'label': 'Neonatal mortality rate (inborn)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Total inborn neonatal unit deaths / Total inborn neonatal unit admissions. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_mortality_by_birthweight_inborn',
         'label': 'Mortality by birthweight (inborn)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn neonatal unit deaths per birthweight band / Inborn neonatal unit admissions per birthweight band. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), '
                 'last updated 3 Aug 2026.'},
        {'id': 'nest360_cpap_timing_birth_inborn',
         'label': 'Time: Birth to CPAP initiation, inborn (1000-1999g)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies 1000-1999g who received CPAP, by time from birth to initiation / Inborn babies (1000-1999g) who received CPAP. Per NEST-IT Clinical & Implementation Indicators Guide '
                 '(Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_kmc_timing_inborn',
         'label': 'Time: Birth to KMC initiation, inborn (1000-2500g)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies who received KMC, by time to initiation (same day/early 1-3d/delayed 3-7d/late >7d/missing) / Total inborn babies who received KMC. Per NEST-IT Clinical & Implementation '
                 'Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug 2026. Malawi, Nigeria, Tanzania and Ethiopia.'},
        {'id': 'nest360_exclusive_breastmilk_discharge_inborn',
         'label': 'Exclusive breastmilk at discharge, inborn',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies exclusively on breastmilk at discharge / Inborn admissions with complete feeding-at-discharge data. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide '
                 '(1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_not_hypoglycemic_admission_inborn',
         'label': 'Not hypoglycemic on admission, inborn',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies not hypoglycemic (blood sugar <=2.5mmol/L / 45mg/dL is hypoglycemic) / Inborn babies with documented blood sugar. Per NEST-IT Clinical & Implementation Indicators Guide '
                 '(Indicators Guide (1).docx), last updated 3 Aug 2026.'},
        {'id': 'nest360_antenatal_corticosteroids',
         'label': 'Antenatal corticosteroids (ACS)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Number of mothers who received ACS / Number of babies with gestational age <34 weeks. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug '
                 '2026.'},
        {'id': 'nest360_hie_rate',
         'label': 'Hypoxic ischemic encephalopathy (HIE)',
         'category': 'Nest360',
         'subcategory': 'Maternal-Newborn Dyad',
         'target': None,
         'status': 'awaiting_baseline',
         'note': 'Inborn babies with a primary discharge diagnosis of HIE / Number of inborn babies. Per NEST-IT Clinical & Implementation Indicators Guide (Indicators Guide (1).docx), last updated 3 Aug '
                 '2026.'},

        # --- Birth weight ------------------------------------------------
        {'id': 'nest360_birth_weight_recorded',
         'label': 'Birth weight recorded',
         'category': 'Nest360',
         'subcategory': 'Birth weight',
         'target': 80,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'Birth weight'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_low_birthweight_rate',
         'label': 'Low birthweight rate (<2500g)',
         'category': 'Nest360',
         'subcategory': 'Birth weight',
         'target': 12,
         'status': 'tracked',
         'target_mode': 'min',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_low_birthweight', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'concept_name', 'value1': 'Birth weight'}},

        # --- Resuscitation -----------------------------------------------
        {'id': 'nest360_birth_asphyxia_rate',
         'label': 'Birth asphyxia among admissions',
         'category': 'Nest360',
         'subcategory': 'Resuscitation',
         'target': 10,
         'status': 'tracked',
         'target_mode': 'min',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_birth_asphyxia', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'Service_Area', 'value1': 'Newborn'}},
        {'id': 'nest360_resuscitation_given',
         'label': 'Eligible babies receiving bag-mask ventilation',
         'category': 'Nest360',
         'subcategory': 'Resuscitation',
         'target': 80,
         'status': 'tracked',
         'numerator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_asphyxia_resuscitated', 'value1': 'Yes'},
         'denominator_filters': {'unique': 'person_id', 'variable1': 'mnid_newborn_birth_asphyxia', 'value1': 'Yes'}},
    ]
